### ISSUE TITLE
Feature Request - x-folder.component

### ISSUE THREAD

**Issue by baiqunicui** [Naoray/laravel-goto-components#2]
Hello, you help me a lot for this plugins, thank you, can you provide regex for x-folder.component
it's mean if we want put component in a folders

resources
  components
    menu
      mobile

so i can call with x-menu.mobile

thanks you

**Comment by Naoray** [comment]
This works already as long as the component is within the `resources/views/components`. You would want to customize this as far as I understand?!

**Comment by baiqunicui** [comment]
im so sorry because i have

resources
components
01menu
mobile

its my fault, thank you

note: done with (?<=<x-)(?!slot)[0-99 a-z.-]+
